Various docs updates, changelog update
UE4SS-RE/RE-UE4SS pull request #355
Opened 2024-02-07 16:36 UTC by Buckminsterfullerene02

added up to date locations in api.txt

make sure all .vscode files are ignored

repo template readme updated for new domain

Update installation guide to be inline with 3.0

devlogs and bp macros pages

update pages for 3.0

update changelog with docs changes and backport the stuff not added in before

2024-02-07 17:25 UTC, UE4SS requested changes

2024-02-07 17:25 UTC, UE4SS commented on docs/cpp-api/bp-macros.md
> +Helper for copying a TArray. (Marked in [BPMacros.hpp](https://github.com/Re-UE4SS/UEPseudo/blob/main/include/Unreal/BPMacros.hpp) as needing more testing, so I probably didn't test it thoroughly)
Note for you left in, probably shouldn't be here or at least formatted in a more generic way that it needs testing.

2024-02-07 21:08 UTC, UE4SS approved these changes

2024-02-07 21:28 UTC, merged

2024-11-09 23:46 UTC, Wanat24TH commented
good bro