Clarify Lua metamethod usage for some classes; Minor docs edits
UE4SS-RE/RE-UE4SS pull request #376
Opened 2024-02-10 12:59 UTC by Lyrth

Resolves #374 

- Clarified usage of `__index`, `__newindex`, `__call` in multiple classes, placing them in a separate Metamethods category.
- Added `__len` metamethod description for TArray.
- UFunction `__call`: mention return val and specify the need for a context parameter if not part of an object instance.
- UObject `__index`: added example of a UFunction call.
- UObject `type()`: clarify that `type(object)` is not equivalent.
- Minor edits (spelling)

For initial review.

2024-02-10 13:12 UTC, UE4SS requested changes
I have requested a bunch of changes where the syntax is wrong but the casing is also wrong in most places.

In general, I believe we're using PascalCase for variable names in the docs and UECase for UE types, and where appropriate the UE type without the type.
Meaning that if the UE type is `UFunction` and if you're referring to the type then put use `UFunction` never `ufunction`, but if you're referring perhaps to the general concept of a function then `Function` would be fine.
I know we're a bit inconsistent with this, the UObject docs for example has this: `CallFunction(UFunction function, auto Params...)` and ideally "f" should've been "F" for the first param.

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uobject.md
> +- **Usage:** `object[objectMemberVarName]` or `object.ObjectMemberName`
This syntax is wrong.
It should be:
```suggestion
- **Usage:** `object["ObjectMemberVarName"]` or `object.ObjectMemberName`
```

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uobject.md
> +- **Usage:** `object[objectMemberVarName] = newValue` or `object.ObjectMemberName = newValue`
This syntax is wrong.
It should be:
```suggestion
- **Usage:** `object["ObjectMemberVarName"] = newValue` or `object.ObjectMemberName = newValue`
```

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uobject.md
> +- Identical to `__index` metamethod (doing `object[MemberVariableName]`)
This syntax is wrong.
It should be:
```suggestion
- Identical to `__index` metamethod (doing `object["MemberVariableName"]`)
```

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uobject.md
> +- Identical to `__newindex` metamethod (doing `object[MemberVariableName] = NewValue`)
This syntax is wrong.
It should be:
```suggestion
- Identical to `__newindex` metamethod (doing `object["MemberVariableName"] = NewValue`)
```

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uscriptstruct.md
> +- **Usage:** `struct[structMemberVarName]` or `struct.StructMemberName`
This syntax is wrong.
It should be:
```suggestion
- **Usage:** `struct["StructMemberVarName"]` or `struct.StructMemberName`
```

2024-02-10 13:12 UTC, UE4SS commented on docs/lua-api/classes/uscriptstruct.md
> +- **Usage:** `struct[structMemberVarName] = newValue` or `struct.StructMemberName = newValue`
This syntax is wrong.
It should be:
```suggestion
- **Usage:** `struct["StructMemberVarName"] = newValue` or `struct.StructMemberName = newValue`
```

2024-02-10 13:46 UTC, Lyrth commented
> I have requested a bunch of changes where the syntax is wrong but the casing is also wrong in most places.

As for the indexing syntax changes, I originally intended for it to show passing in a string *variable* as the index (as opposed to passing in a string literal, hence the different casing and name, e.g. structMember**Var**Name variable vs. StructMemberName literal on the second usage).

Although on second thought, a string literal would be less confusing and better overall as it also implies that the index is a string value in general. I will make changes to those usages.

I will also make changes to the casing of the variables, e.g. `ufunction(...)` -> `UFunction(...)`, and probably for ones with __index too, as in `object[objectMemberVarName] = newValue` -> `UObject["ObjectMemberName"] = NewValue`, unless the former's currently fine.

2024-02-10 22:40 UTC, UE4SS commented
> > I have requested a bunch of changes where the syntax is wrong but the casing is also wrong in most places.
> 
> As for the indexing syntax changes, I originally intended for it to show passing in a string _variable_ as the index (as opposed to passing in a string literal, hence the different casing and name, e.g. structMember**Var**Name variable vs. StructMemberName literal on the second usage).
> 
> Although on second thought, a string literal would be less confusing and better overall as it also implies that the index is a string value in general. I will make changes to those usages.
> 
> I will also make changes to the casing of the variables, e.g. `ufunction(...)` -> `UFunction(...)`, and probably for ones with __index too, as in `object[objectMemberVarName] = newValue` -> `UObject["ObjectMemberName"] = NewValue`, unless the former's currently fine.

All your proposed changes look good.

2024-02-11 05:00 UTC, Lyrth commented
- Applied changes
- Fixed `UObject:CallFunction` param casing (`UFunction function` -> `UFunction Function`)

2024-02-11 08:53 UTC, UE4SS approved these changes

2024-02-11 12:43 UTC, merged