feat(lua): print now prints any value, accepts multiple params
UE4SS-RE/RE-UE4SS pull request #423
Opened 2024-03-04 18:07 UTC by Lyrth

**Description**

`print` in Lua can now accept any type without throwing an error. Additionally, `print` can now accept varargs - any number (within reason ofc) of (possibly mixed) arguments, which will be printed out into the console with each argument separated by tab(s). This is basically vanilla Lua behavior for `print` on a terminal.

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Print basically any type including UE4SS types, with varying amount of arguments, and also do mixed arguments.
P.S. Zero args print empty `[Lua] ` line, also similar to vanilla Lua behavior.
<details>
<summary>[ Script used for testing ]</summary>

```lua
    local ksl = StaticFindObject("/Script/Engine.Default__KismetStringLibrary")
    local act = FindFirstOf("Actor")
    local inv = FindFirstOf("INVALIDOBJECT").fhvgh23vyf7f4tv7v873vf723vf7823vf7v37116ffv3

    print("-----")
    print("-----")
    print("-----")

    print("Hello 1234")
    print(1234)
    print(true)
    print(ksl)
    print(inv)
    print({})
    print("")
    print()

    print("-----")

    print("Hello 123", "Hello 456")
    print(12, 34, 56, 78)
    print("Aa", "Bb", "Cc", "Dd")
    print("", "", "", "")
    print(nil)
    print(nil, nil)

    print("-----")

    print(0, nil, false, "", print)
    print({}, ksl, act, coroutine.create(print))

    local t = {0, nil, false, ""}
    print(table.unpack(t))

    print("-----")
    print("-----")
    print("-----")
```
</details>

Unable to test `FOutputDevice->Log()` as I don't have a game that shows me a full-view console. Although, enabling the Lua executor with `luastart` and printing stuff out does not crash, and the `FOutputDevice->Log()` line seems to be ran with each print (`output_device` is non-null).

**Checklist**

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.
- [x] Any dependent changes have been merged and published in downstream modules.

**Screenshots**

![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/38674984/a20ecc41-495d-4c33-b0b4-e402ac43fdbf)

**Additional context**
- `print(string Message)` in docs is changed to `print(any... Message)` signifying varargs of type any.
- Specified "New lines are not automatically appended _to the log file_" since the log file is the only place where the newlines disappear, UE4SS console appears fine (I don't know about how FOutputDevice will output it).
- (hope you don't mind the whitespace being dealt with by my editor).

2024-03-04 19:22 UTC, UE4SS commented
The FOutputDevice stuff is a completely separate system and never interacts with our own logging system or Luas print function.
Any output via FOutputDevice to the UE console is unchanged by this PR.

2024-03-04 19:32 UTC, UE4SS commented
The UE console can't handle `\t` apparently.
Output with the Lua executor looks like this:
![2024-03-04_20-30_luaconsole](https://github.com/UE4SS-RE/RE-UE4SS/assets/91646798/78f24824-7722-4f8a-9a21-e09d3fa13408)

2024-03-05 00:01 UTC, UE4SS requested changes

2024-03-05 00:01 UTC, UE4SS commented on docs/lua-api/global-functions/print.md
> +| ... | any   | String to output |
```suggestion
| ... | any   | String or variable to output |
```

2024-03-05 00:50 UTC, Lyrth commented
> The UE console can't handle `\t` apparently. Output with the Lua executor looks like this: ![2024-03-04_20-30_luaconsole](https://private-user-images.githubusercontent.com/91646798/309877835-78f24824-7722-4f8a-9a21-e09d3fa13408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTg3OTIsIm5iZiI6MTcwOTU5ODQ5MiwicGF0aCI6Ii85MTY0Njc5OC8zMDk4Nzc4MzUtNzhmMjQ4MjQtNzcyMi00ZjhhLTlhMjEtZTA5ZDNmYTEzNDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAwMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMGI1MmZiNDljNTNmZjAyMDRiZmFkOWQzMWVhNzg4NjJlYWZkNjU1ZDE5Y2ViZWViYTQxMjNkMGMzNjAxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmQFEr2MpK8xD4jquxUfaN8y45h3SGRSmng_1EZoPhc)

Ah, unfortunate

Can we perhaps just construct two separate strings, one that uses tabs for the UE4SS console, other with spaces for the FOutputDevice?
(I kind of want to use tabs since they get aligned in the UE4SS console nicely, despite the non-monospace font. But that's entirely only my visual preference)

2024-03-05 00:54 UTC, UE4SS commented
> > The UE console can't handle `\t` apparently. Output with the Lua executor looks like this: ![2024-03-04_20-30_luaconsole](https://private-user-images.githubusercontent.com/91646798/309877835-78f24824-7722-4f8a-9a21-e09d3fa13408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTg3OTIsIm5iZiI6MTcwOTU5ODQ5MiwicGF0aCI6Ii85MTY0Njc5OC8zMDk4Nzc4MzUtNzhmMjQ4MjQtNzcyMi00ZjhhLTlhMjEtZTA5ZDNmYTEzNDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAwMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMGI1MmZiNDljNTNmZjAyMDRiZmFkOWQzMWVhNzg4NjJlYWZkNjU1ZDE5Y2ViZWViYTQxMjNkMGMzNjAxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmQFEr2MpK8xD4jquxUfaN8y45h3SGRSmng_1EZoPhc)
> 
> Ah, unfortunate
> 
> Can we perhaps just construct two separate strings, one that uses tabs for the UE4SS console, other with spaces for the FOutputDevice? (I kind of want to use tabs since they get aligned in the UE4SS console nicely, despite the non-monospace font. But that's entirely only my visual preference)

I'd say that's acceptable, but we should probably check if there is an FOutputDevice before operating on the second string, small thing but why not, there's no reason to fill up another string if it's not going to be used.
Meaning, move `auto* output_device = get_outputdevice_ref(lua);` to the top of the function so that it can be checked for nullptr inside the loop.

2024-03-05 00:55 UTC, UE4SS commented on UE4SS/src/LuaLibrary.cpp
> +                formatted_string.append(STR("\t\t"));
Resolved here: https://github.com/UE4SS-RE/RE-UE4SS/pull/423#issuecomment-1977745304 and the comment immediately after.

2024-03-05 02:19 UTC, Lyrth commented
Requested revisions applied.

2024-03-05 04:26 UTC, UE4SS approved these changes

2024-03-05 09:04 UTC, merged