fix(BPModLoader): Loading on slow dedicated servers
UE4SS-RE/RE-UE4SS pull request #454
Opened 2024-04-05 21:22 UTC by localcc

**Description**

Fixes loading on slow dedicated servers where UE4SS initializes too
late.

Fixes # (issue) (if applicable)

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Is/requires documentation update
- [ ] Other... Please describe:

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so reviewers can reproduce. Please also list any relevant details for your test configuration.

**Checklist**

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.
- [x] Any dependent changes have been merged and published in downstream modules.

**Screenshots (if appropriate)**

**Additional context**

2024-04-05 21:25 UTC, UE4SS requested changes

2024-04-05 21:25 UTC, UE4SS commented on assets/Mods/BPModLoaderMod/Scripts/main.lua
> +end
```suggestion
local ExistingActor = FindFirstOf("Actor")
if ExistingActor ~= nil and ExistingActor:IsValid() then
    LoadMods(ExistingActor:GetWorld())
end
```
Typos.

2024-04-05 21:32 UTC, UE4SS commented
Are we absolutely sure that the first actor that exists in GUObjectArray always belongs to the correct world ?
I looked at a similar fix but I didn't want to move forward because I didn't have the answer to the above question and I didn't feel like firing up 100 games to test it nor did I feel like looking forever at the UE source code to figure it out.

2024-04-05 22:07 UTC, localcc commented
When testing I didn't have any issues, and it doesn't matter if it's not in the correct world yet, because an even for changing worlds will fire which should respawn the mod actors.

2024-04-05 22:08 UTC, UE4SS approved these changes

2024-04-05 23:45 UTC, UE4SS commented
Changelog entry is missing, even though the checkbox for it is ticked.

2024-04-06 07:10 UTC, Buckminsterfullerene02 commented
Why did you have to base this branch off of a really old commit 😂

2024-04-06 07:11 UTC, merged