Added global lua function CreateBlankObject (#652)
UE4SS-RE/RE-UE4SS pull request #666
Opened 2024-09-27 12:42 UTC by igromanru

Resolves #652

**Testing**
Built UE4SS and deployed in Abiotic Factor.
Tested with Lua code:
```lua
local blankObject = CreateBlankObject()
print("blankObject varibale type: " .. type(blankObject))
if blankObject then
	print("blankObject userdata type: " .. blankObject:type())
	print("blankObject IsValid:" .. tostring(blankObject:IsValid()))
end
```
Result:  
```
[12:40:32.1231285] [Lua] blankObject varibale type: userdata
[12:40:32.1231360] [Lua] blankObject userdata type: UObject
[12:40:32.1231428] [Lua] blankObject IsValid:false
```

**Additional**
Fixed `FindFirstOf` return type annotation in `Types.lua`

2024-09-27 12:46 UTC, UE4SS requested changes

2024-09-27 12:46 UTC, UE4SS commented on assets/Changelog.md
> +Added global function `CreateBlankObject`, which returns an empty UObject. ([UE4SS #652](https://github.com/UE4SS-RE/RE-UE4SS/issues/652))
```suggestion
Added global function `CreateBlankObject`, which returns an invalid UObject. ([UE4SS #652](https://github.com/UE4SS-RE/RE-UE4SS/issues/652)) 
```
I think this makes more sense.
I don't think "empty" makes it clear what the purpose of this function is.

2024-09-28 09:05 UTC, igromanru commented
Can someone just Clone the branch from my fork, compile and test it locally, then just force merge?

2024-09-28 12:22 UTC, UE4SS approved these changes

2024-09-30 17:54 UTC, narknon commented
I think "Blank" is a bit confusing.  Maybe dummy or empty?

2024-09-30 17:57 UTC, UE4SS commented
> I think "Blank" is a bit confusing. Maybe dummy or empty?

Perhaps "CreateInvalidObject" is even more accurate to what the function actually does ?

2024-09-30 17:59 UTC, narknon commented
I guess CreateInvalidLuaUObject is too verbose

2024-09-30 18:02 UTC, UE4SS commented
> I guess CreateInvalidLuaUObject is too verbose

Yeah I don't think "LuaU" is necessary, and besides, we might reuse this function at some point for non-UObject stuff so it's nice to keep the "U" out of "Object".
It really doesn't have anything to do with UObject anyway, it's just a function implemented for UObjects among other objects.

2024-09-30 18:31 UTC, igromanru commented
Tested;
```lua
local invalidObject = CreateInvalidObject()
print("blankObject variable type: " .. type(invalidObject))
if invalidObject then
	print("blankObject userdata type: " .. invalidObject:type())
	print("blankObject IsValid: " .. tostring(invalidObject:IsValid()))
end
```
Result:  
```
blankObject variable type: userdata
blankObject userdata type: UObject
blankObject IsValid: false
```

2024-09-30 18:33 UTC, UE4SS approved these changes

2024-10-01 17:03 UTC, merged